"""Add ip_id and intel relationship to alerts

Revision ID: 40827590107e
Revises: 57a5a8b198c6
Create Date: 2025-06-11 10:48:43.068644

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40827590107e'
down_revision: Union[str, None] = '57a5a8b198c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print("📢 Inside migration file")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertfordb', sa.Column(
        'ip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alertfordb',
                          'failedloginintel', ['ip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alertfordb', type_='foreignkey')
    op.drop_column('alertfordb', 'ip_id')
    # ### end Alembic commands ###
