"""Initial schema

Revision ID: 57a5a8b198c6
Revises: 
Create Date: 2025-06-11 10:27:55.219956

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57a5a8b198c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertfordb',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('alert_type', sa.Enum('ip_analyzed',
                              name='alerttype_enum'), nullable=True),
                    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.Enum('unread', 'read',
                                                name='alertstatus_enum'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=1000),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=1000),
                    nullable=False)
    op.drop_table('alertfordb')
    # ### end Alembic commands ###
